services:

  db:
    image: postgres
    container_name: db
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    network_mode: "host"
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Persist data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chemical"]
      interval: 10s
      timeout: 5s
      retries: 5

  sim_api:
    image: sim_api:latest
    container_name: sim_api
    ports:
      - "5050:5050"
    environment:
      - FASTAPI_ENV=${FASTAPI_ENV:-DEV}
      - PG_HOST=0.0.0.0
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=example
      - PG_DATABASE=chemical
    depends_on:
      - db
    network_mode: "host"
  sim_ir:
    image: sim_ir:latest
    container_name: sim_ir
    ports:
      - "5051:5051"
    environment:
      - FASTAPI_ENV=${FASTAPI_ENV:-DEV}
    network_mode: "host"

  qdrant:
    image: qdrant/qdrant:master
    container_name: qdrant_container
    restart: unless-stopped
    ports:
      - "6333:6333"  # Qdrant default HTTP port
      - "6334:6334"  # Qdrant default gRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage  # Persisting data on host
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
